version: '3'
services:
  app:
    build: .
    ports:
      - '5000:5000'
    volumes:
      - ./app.py:/app/app.py
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_NAME=mydb
      - DATABASE_USER=myuser
      - DATABASE_PASSWORD=mypassword
    depends_on:
      - database

  database:
    image: postgres:13
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
